### ISSUE TITLE
Inconsistent GitHub tagging behaviour between FINOS contributors

### ISSUE THREAD

**Issue by mcleo-d** [finos/open-developer-platform#70] opened 2020-02-13 11:30 UTC
### Issue Description
FINOS project members are experiencing different tagging behaviours when engaging with project contributors that aren't members of the FINOS organisation. 

Can we get your awesome GitHub insight @brntbeer? 😄👍
 
### Failing Tagging Scenario
For example, within the comments of https://github.com/finos/FDC3/pull/171, @rikoe cannot tag @vmehtafds in the comments using the intelligent dropdown. See screenshot by @rikoe. 

![GitHub chat](https://user-images.githubusercontent.com/6029572/74427780-a7092a00-4e4f-11ea-9b89-c15f129e255e.png)

### Succesful Tagging Scenario
However, @mcleo-d doesn't experience @rikoe's problem and can tag @vmehtafds easily. See screenshot below.

<img width="871" alt="Screenshot 2020-02-13 at 10 33 34" src="https://user-images.githubusercontent.com/6029572/74427843-c56f2580-4e4f-11ea-9325-88edf26363f3.png">

### Questions to Answer
* Are tagging behaviours different between individual contributors in GitHub?
* Is @mcleo-d's role in https://github.com/finos influencing his ability to tag @vmehtafds compared to @rikoe?

**Comment by brntbeer** [comment] 2020-02-13 14:37
@mcleo-d i need to be added as an admin onto that repo to see things like what @rikoe's permission level is on that repository and in that organization, etc.

I also can't really trouble shoot this as it could just as easily be a javascript issue of loading. Is this repeatable? does it happen all of the time? 

@rikoe's username also doesn't appear for me on this issue as i go to @mention him because he's not a member of the organization or otherwise a collaborator on this given issue. GitHub's autocomplete isn't going to auto-complete for all users across all of GitHub when typing, I think the priority is organization members => collaborators on the repository => other people in the current thread but i'm just guessing

**Comment by brntbeer** [comment] 2020-02-13 14:44
Followup here. I can see that `@vmehtafds` is not a collaborator on any repositories, is not a member of any organizations, but has otherwise just been marked as a reviewer. that can be my only guess as to why the autocomplete is not working 🤷‍♂

**Comment by rikoe** [comment] 2020-02-13 14:52
This is the issue though. I am a member of the org, and an admin on the project, so I should at least show up.

Vinod is not an official collaborator on the project. But his name or user id doesn't even auto-complete if I try to tag him _in a comment of a message he posted himself_.

The problem is that if autocomplete doesn't work, I can't tag someone by name (e.g. "Vinod") - I have to remember or copy and paste their full user id. Most other GH repos I work on I have never had these issues, I can tag, add people as reviewers etc. without trouble, regardless of whether they are necessarily "members" or not.

**Comment by mcleo-d** [comment] 2020-02-14 12:34
@brntbeer and @rikoe - Thanks so much for debugging the issue together. @maoo is on annual leave at the moment, so granting org and repo access will need to wait until his return. 

In the meantime, I've changed the issue status to **In Progress** so it's on the radar as we schedule the next ODP WG session.

Cheers!

**Comment by maoo** [comment] 2020-02-17 20:38
@rikoe - thanks for creating this issue, I think it makes total sense to address this issue as part of the ODP initiative.

> Followup here. I can see that @vmehtafds is not a collaborator on any repositories, is not a member of any organizations, but has otherwise just been marked as a reviewer. that can be my only guess as to why the autocomplete is not working 🤷‍♂

I've seen this behaviour being consistent across all the (10+) GitHub Orgs I manage: non-members cannot be mentioned in issues, nor be assignees or reviewers.

At FINOS, we use GitHub membership to identify all those GitHub users that are covered by a CLA contract with us, which is why we cannot add everyone we'd like to as members.

@brntbeer - What is the rationale behind this behaviour? Why non-members cannot be issue assignees or reviewers? I've checked the `Members Privileges` configuration and couldn't find any setting for non-members; it would be great to have a flag there that to `Allow non-members to be @ mentioned in issues and PRs` (or similar).

Could you please investigate this further internally and:
1. Confirm this is the expected behaviour
2. Check if other GitHub.com customers have requested such feature, or
3. Submit a new feature request for GitHub.com

Please let me know how I can be of support! TY.

**Comment by mcleo-d** [comment] 2020-02-18 12:21
@maoo and @brntbeer - Is this issue a discussion topic for the next ODP meeting as I'm happy to help close on an ODP call with @rikoe.

I'd be happy if the closing action's a FINOS support story on the GitHub backlog for the GH team to pick up internally?

Let me know your thoughts and I'll place on the next agenda.

James.

**Comment by maoo** [comment] 2020-02-26 17:15
@issc29 - thanks for today's ODP call, please keep us posted here with your discoveries.

**Comment by mammamao** [comment] 2020-03-18 13:36
This is @maoo . Adding a comment from a non-member (test) account

**Comment by maoo** [comment] 2020-03-18 13:38
@rikoe - here's an interesting update; I've consolidated GitHub documentation on https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/75530554/Code+Hosting (eager to hear your feedback!) and found out that _anyone who left a comment on the issue can be engaged as Issue and Pull Request reviewer/assignee_ .

As you can see, I've added a comment above from an account that is not part of https://github.com/orgs/finos/people , and now @mammamao can be tagged and used as issue assignee/reporter . 

Hope this solves your issue!

**Comment by maoo** [comment] 2020-03-23 15:56
I'm going to mask this issue as closed, feel free to reopen if needed.

**Closed by maoo** 2020-03-23 15:56 UTC
Labels: atomic, prio-medium, question
